### PR TITLE
identified potential areas for changes with '//LOOKHERE' comment

### PR DESCRIPTION
**Pull request by vaniahalim**
USAGE:
- search keyword "LOOKHERE" to find all areas with potential changes
- identified lines of code in document may have shifted with the added comment lines

IMPORTANT FILES:
1. apexcharts.js
2. src/charts/BarStacked.js (creates stacked bars/columns)
3. src/modules/settings/Options.js (defines options for charts) e.g. borderRadiusApplication, borderRadiusWhenStacked

NOTE:
- variables to consider
1. borderRadiusApplication
3. borderRadiusWhenStacked
4. shouldApplyRadius
- nonexhaustive: only identified possible areas

### CODE REVIEW

**Comment by AvaGivone** [comment]
Great, thanks Vania!

**Review by AvaGivone — APPROVED** [review]
Great, thanks Vania!

**Review by nehatirumalai — APPROVED** [review]
Looks good!

**Review by Gbenuola-Olaiya — APPROVED** [review]
Looks good! Thank you, Vania!

**Review by abbyrchen — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
